default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tulenmenu_development

test:
  <<: *default
  database: tulenmenu_test

production:
  <<: *default
